# Generated by Django 5.2.3 on 2025-07-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIN', models.IntegerField()),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=3)),
                ('Branch', models.CharField(max_length=20)),
                ('College', models.CharField(max_length=100)),
            ],
        ),
    ]
